### ISSUE TITLE
[1.1.4f] Pressure Chamber Interface problems

### ISSUE THREAD

**Issue by KeepOnDigging** [MineMaarten/PneumaticCraft#132]
I am playing the Crash Landing FTB pack/map, and since Iskandar has used Pneumaticraft items (PCBs) a gate before you can achieve automation, I have been introduced to PneumatiCraft. 

You have some great ideas in this mod, and I'm actually starting to look forward to learning more about it, but I have come across some problems.

The first is that Pressure Chamber Interfaces just don't work. I have two pressure interfaces on a 1x1x1 Pressure Chamber. Yes they are facing the right way!

On the input side, I have an itemduct connecting a chest to the Interface. Itemduct is set to be always on. 

If I'm making a single small item, like a bucket of etching acid, the Interface seems to work OK.

But if I make a large batch of something (like if I throw a stack of compressed iron and a stack of black plastic into the chest), the interface gets stuck. One stack of items goes in, the interface doors cycle but the stack of items never enters the Chamber. Then the other components cannot be inserted and the crafting doesn't happen. I have to break the Interface to recover my items.

The limit seems to be 8 items at a time. Any more than 8 items in a stack and it gets stuck.

The second problem… if I place my items into the chest 8 items at a time, every time the Interface cycles the pressure drops back to 0. My understanding of the Interface is that it allows items to be inserted/extracted without loss of pressure. Well that's not working, if indeed that's what it's supposed to do.

Also, the extraction interface also drops the pressure to 0 every time it cycles as well.

So if I'm crafting a stack of transistors, inserting items 8 at a time into the Chamber through the interfaces takes ages because I keep losing pressure. 6 minutes to craft the stack would be my estimate.

If I just break the chamber, throw the 2 stacks in, then rebuild the chamber and add coal… the process is complete within a minute. But breaking the chamber all the time just seems like the wrong thing to so, when the Interfaces are there to help.

One last problem with Interfaces… the Extraction interface only works sometimes. It seems to only be able to extract items which finish up on it's half of the centre space. If the item is over the far side of the space, again I need to break the Chamber to get the items out.

More bug reports to come…

Thanks for this interesting mod,
KeepOnDigging!

**Comment by ghost** [comment]
for me the interface dosnt work at all wen using the interface it will just trow out the items out how they came in.....

**Comment by MaartenKok8** [comment]
Make sure you filter the outputting Pressure Chamber Interface, so that it only extracts finished products. I know this is a bit annoying, and is on our list to fix soon. There's a reason for it:

"The extraction of items from a Pressure Chamber with a filtered Pressure Chamber Interface is annoying to manage, stemming from the fact that compressed iron could be a desired result item, or just a component of another recipe in a Pressure Chamber. The Interface does not know which is desired."

If you btw have any future issues, please report them to https://github.com/TeamPneumatic/pnc-repressurized/issues instead. Thanks.

**Comment by Tekstack** [comment]
@MineMaarten  you can move this / delete, but I thought this would be the appropriate place to put mention in context. I have always gotten around the filter of compressed iron issue by using iron blocks to make compressed iron blocks that are then broken down to ingots since the blocks are not used in any pressure chamber recipe. It makes for easy automation with AE or refined storage without worring about the ingots being pulled out prematurely. Hope this helps :)

**Comment by MaartenKok8** [comment]
Yes, this strategy was mentioned to me after the rebalancing suggestion I quoted a piece from above. I didn't realize this was an option (I was outsmarted on my own mod :P). In my playthroughs I would be using two pressure chambers, one of which was purely making compressed iron.

So knowing this, one solution would be to better convey this strategy to players, maybe by even removing the `iron ingot -> compressed iron ingot` recipe altogether, and just leave the block recipe. That would allow removing the whole requirement for having filters in the Pressure Chamber Interfaces altogether, as they then could just filter on items that are output items of recipes.

If you have any other suggestions, or comments about what I just said, be sure to add it here https://github.com/TeamPneumatic/pnc-repressurized/issues/130 . We are looking at doing a overall rebalance of the mod, and community input is very much appreciated, and I know you in particular, @Tekstack , have played quite a bit with PC from what I have seen, so if there's stuff you would like to see different in terms of balance, or have comments about what I'm proposing (see the issue), I'd like to hear :)
