### ISSUE TITLE
block right-click not working

### ISSUE THREAD

**Issue by Nikel90** [MineMaarten/PneumaticCraft#383]
pneumaticcraft 1.5.2-50 the block right click programming piece is not working with nether warth or any seeds.

it also does not work with extra-utilities oreberrys (in this case it does right click but does not collect berries)

**Comment by MineMaarten** [comment]
About the nether ward / seeds, I tested it, it works. For it to work you have to make sure you've set the right click block to right click to the top of the block, instead of the bottom (which is the default).

Ore berries behaviour is intentional, it should drop the berries but not suck them up. Use a item pick-up to fix.

**Comment by Nikel90** [comment]
oreberries are transferred directly into player inventory (not dropped) but the drone can't collect them.

(for nether wart and seeds, ty didn't know the "top-option")

**Comment by MineMaarten** [comment]
Ok tnx for the clarification, I tested it and you're right. now I've implemented it so that the drone will drop any XP orbs it collects in its fake player. This fix will be included in the upcoming version.
