### ISSUE TITLE
Pnuematicraft seeds and ritual of the green grove

### ISSUE THREAD

**Issue by thunder1221sa** [MineMaarten/PneumaticCraft#386]
I am automating the production of plastic seeds using the ritual of the green grove(Blood Magic) It seems that the squid and rain plant seeds are affected by the ritual, but the burst, slime, and creeper plant seeds are not. There may be more but that's what 's happening for me.

**Comment by DarkStarDS9** [comment]
Actually, it should work the same way for all PC plants: it waters the soil, thus increasing the chance of growth. The ritual would't speed up growth by calling the tick-handler, because it only checks for IPlantable, which PC plants don't implement. IIRC this could be added for PC plants though (but it can't be added for seeds). Why this would have any effect on squid plants eludes me.

Still, you may want to suggest to [WayofTime/BloodMagic](https://github.com/WayofTime/BloodMagic/issues) to (also) check for IGrowable - this would potentially catch more plants, and would also give him more options (e.g. cause bonemeal-like instant growth via func_149853_b) if that's his thing. A pointer to [this thread on minecraftforge](http://www.minecraftforge.net/forum/index.php?topic=22571.0) might shed some light on the different functions.

**Comment by Sciencei** [comment]
Actually... ofc now that I've submitted the PR to BM (not that IGrowable support is a bad thing), upon further inspection, PC plants extend BlockPneumaticPlantBase, which extends BlockFlower, which extends BlockBush, which implements IPlantable. So that *shouldn't* be the issue.

**Comment by MineMaarten** [comment]
are you absolutely sure the ritual doesn't work on some plants? Might it be that the plants look not full grown, because they've executed their full grown effect (and therefore go a few growth steps back)?

**Comment by DarkStarDS9** [comment]
whoops - sorry about that... well, that explains why it works for Squid Plants then.
So... what MineMaarten said :) Also, maybe post a screenshot of your setup; light level (of the block above, also see #379) and neighboring plants are both influencing growth.
