### ISSUE TITLE
[Config Request] Making Drone insta-teleportation optional

### ISSUE THREAD

**Issue by BarbasTheDog** [MineMaarten/PneumaticCraft#392]
Right now there's no way that I'm aware of to turn off the insta-teleportation that happens when a drone cannot pathfind to its destiny.

This could possibly be exploited as a means of long-distance transportation of items in packs that have the player rely on minecarts or similar methods for such transport.

**Comment by MineMaarten** [comment]
It should be anything but a config option. A balancing thing like this shouldn't be a config option.

The reason that I implemented the teleporting in the first place is because it would lag out servers when a drone continually tries to pathfind and fail. Simply giving the drone a 'time penalty' when failing, and retrying would just be seen as a bug. Likewise would it be annoying if a Drone wouldn't be able to return from quarrying a hole of 60 blocks deep.

Conclusion: I won't implement it, as it would cause problems. I don't want to do that just for balancing reasons. Which is why the drone is using 1 bar per teleport.

Sorry!

**Comment by BarbasTheDog** [comment]
Hmm. I didn't realise it was added because of performance. Now I understand why you wouldn't want to add a config for it
