### ISSUE TITLE
Lost Drones on teleport

### ISSUE THREAD

**Issue by SeirVed** [MineMaarten/PneumaticCraft#425]
Made drones and programmed in overworld.
Took them to the end to mine, reprogrammed them to use a chest place in the end.
Output chest was still programmed to overworld base, the paused and teleported to god knows where.
I checked the equivalent coords to overworld base in the end, no sign of them anywhere.

Perhaps some kind of wireless emergency transponder to recall all drones to the players location?
That or have them be able to differentiate dimensions.

**Comment by MineMaarten** [comment]
" I checked the equivalent coords to overworld base in the end, no sign of them anywhere." it should be there. But if it's in the End, it's possible that if it took long, the drone ran out of pressure and fell in the void.

Currently I'm working on a 'Remote'. This allows you to design your own user interface, which controls variables, which can be read from a Drone. This is not a hardcoded solution, you will still need to program the drone to listen to this variable. This would be about 5 more puzzle pieces needed. I do kinda like that.

I think the real issue here is that GPS Tools / areas aren't dimension specific. That should be solved
