### ISSUE TITLE
Gas Lift does not recognize BC oil

### ISSUE THREAD

**Issue by utoc** [MineMaarten/PneumaticCraft#493]
Greetings,

We're running PneumaticCraft 1.8.1-83 with BC 7.0.9 and FML 1448.  Currently PneumaticCraft oil generation is disabled and therefore all oil is BC oil.  Placing a gas lift and powering it causes the BC oil fluid blocks to be destroyed and the gas lift continues to "mine" for oil with no BC oil being recovered.  If I scoop up a bucket of the BC oil and place it back down, it does show up as PneumaticCraft oil and the Gas Lift will recognize it and properly pick it up.

**Comment by MineMaarten** [comment]
Interesting... It appears that PneumaticCraft decided to use its own oil even though BC oil is around.. I think I should make it so that PneumaticCraft loads after BuildCraft if it's in the instance..

About the Seismic Sensor, this is intended behaviour. Due to performance reasons the Seismic Sensor checks for marked chunks (comparable to Slime Chunks for example). BC oil spawns don't mark it (as it's a PneumaticCraft custom thing).

**Comment by utoc** [comment]
I've edited the title and comment to update the intended behavior of the Seismic Sensor.
