### ISSUE TITLE
Add achievements, to at least guide you through the infrastructure

### ISSUE THREAD

**Issue by MineMaarten** [MineMaarten/PneumaticCraft#561]

**Comment by Wolf68k** [comment]
Or a book.
A book would be nice, more so for how to get started since people are too lazy to go to the forums/wiki to find out.
Simple recipe: any pneumaticcraft seed with a vanilla book.
Or you can be as cute as what BloodMagic did with it's book using Guide-API to make a page that you throw on the grown and if (well it would be in this case) PneumaticCraft is in the pack an Amazon drone delivers it then flies off.

**Comment by MineMaarten** [comment]
This doesn't make sense for two reasons:
1. Seeds are being removed.
2. I've got a perfect wiki already, called In-Game Wiki mod, which it fully supports. 

The achievements will serve as a small additional source, and is more a guide than a real tutorial.

**Comment by Wolf68k** [comment]
I never saw anything about seeds being removed. Sorry. I've been so busy with updating a pack and plus the server I play on has reset the world so many times before I can get around to starting the mod that I didn't notice that way either. And the pack currently isn't using In-Game Wiki.
This goes for the other issue I reported too.

**Comment by MineMaarten** [comment]
Well, imo it should be using IGW-Mod.

**Comment by ruifung** [comment]
Heh, It pretty much requires IGW Mod as there doesn't seem to be any other documentation for pneumaticcraft anywhere. (Short of going through the wiki text files for IGWmod/)
