### ISSUE TITLE
Crash with logistic frames.

### ISSUE THREAD

**Issue by Guardian9978** [MineMaarten/PneumaticCraft#649]
I have setup a pneumatic system in a Tardis using the Tardis Mod. Whenever I leave the dimension and return all the frames that were placed appear invisible holding the logistic tool doesn't make them reappear I know they are still there because the drones flying around are still interacting with the inventories the frames are attached to.  if I try to configure a frame I know exists on an inventory I receive this error: http://pastebin.com/eKQ2C3S8

Only way around this issue I have found is to grab another frame and place it on the inventory to replace the existing frame then place the original frame back on the inventory.

Any help to avoid this issue from happening?

**Comment by Forecaster** [comment]
If you re-log while in this dimension does the frames re-appear?

**Comment by Forecaster** [comment]
The crash appears to be the same as #552

**Comment by MineMaarten** [comment]
same crash result, other cause. Problem is that when a GUI crashes, it only gives this obscure crash (for any GUI crash). Luckily in this instance it's obvious the root cause was that logistic frames weren't synced properly from server to client on dimension switching. For the Programmer however, I'm not sure yet. I can't reproduce it (I could with this one).

**Comment by Forecaster** [comment]
Ah, well I've had this happen as well, though I might have forgotten to write a ticket about it
