### ISSUE TITLE
Oil doesn't "behave" as a fluid

### ISSUE THREAD

**Issue by SunshineHunter** [MineMaarten/PneumaticCraft#663]
Hello,
I'm not sure if it's intended behaviour, but the oil isn't "behaving" as a fluid in my modpack. It's flowing, but if you go into it, you aren't swimming. Here's more information about my modpack: http://pastebin.com/U07i0wZ0

**Comment by pyure** [comment]
There's a type of oil that you can't swim in.  I believe its "oilgc" from galacticraft, and I believe its intended.

**Comment by MineMaarten** [comment]
The PneumaticCraft oil also doesn't behave like water, I naively thought that was done automagically by MC.

**Comment by Vexatos** [comment]
@MineMaarten To make players swim as well as drown in water, your oil needs to be `Material.water`.

**Comment by MineMaarten** [comment]
Ah so that broke it. The reason I moved away from using Material.water is because it creates a water exploit when right-clicking bottles on the acid (as ItemGlassBottle checks only for Material.water >.>). In  a normal survival world this is not a big deal, however, in @1skandar 's Crash Landing, this was an issue. So I'm not sure how to tackle this.

I guess making it use Material.water again and catching the PlayerInteracitonEvent and cancel it when right clicking with a bottle. Not sure if that works even.

**Comment by executionByFork** [comment]
This is still an issue in 1.18.2, version 3.6.0-19

https://github.com/MineMaarten/PneumaticCraft/assets/20407804/39657e5a-27bd-4073-8aab-b64936c8d4e6

EDIT: Aplogies, this is not the PneumaticCraft Repressurized github. Will post this issue there.
