### ISSUE TITLE
Add Kerosene lamps

### ISSUE THREAD

**Issue by MineMaarten** [MineMaarten/PneumaticCraft#669]
A genuine use for Kerosene, apart from cracking it into Gasoline.

**Comment by Forecaster** [comment]
As in crafted with kerosene or running on kerosene?

**Comment by MineMaarten** [comment]
Running on, a very low amount. It could easily be refueled using logistic drones if you really wanted to :)

**Comment by Forecaster** [comment]
cool, will fit nicely with my coming "finite lighting" modifications where I'll disable any easily obtained infinite light source.
: D

**Comment by MeshPL** [comment]
It would be cool if those Kerosene Lamps would be "stronger" than regular light sources, like EnderIO powered lights or Thaumcraft arcane lamps. Apart from aesthetical reasons there should be other reasons for player to use such a "finite" light source system.

**Comment by MineMaarten** [comment]
Oh definitely, I had that in mind ;). Possibly even an adjustable range (higher range = more usage)

**Comment by Forecaster** [comment]
I thought you couldn't do that without adding fake air blocks that emit light, fake air blocks have been known to cause issues.

**Comment by MineMaarten** [comment]
Issues related to mods not checking for air properly, of which most of have been solved when having to deal with Railcraft's heat block.

But yes, a fake air block will happen.

**Comment by Axylxys** [comment]
Maybe they could have other special properties, such as scaring mobs away or something. Or at least a normal version (like a basic torch) and an improved one with the air blocks. I know i wouldn't use any lamp functionning with the air block stuff, back in 1.5 i lost a world because of that and i'm probably not the only one scared by those. 

Especially as light isn't exactly hard to come by these days, between glowing multiblocks, carpenter's block, and all mods adding their own flavor of light sources including magical ones. I think it should definitely have a special flair rather than "moooore radius".

Maybe something with drones, such as guiding them (a default point for the drone to idle, which would save the use of a puzzle piece) ? Just some random idea.

**Comment by Forecaster** [comment]
I'm happy with them just being torches that run on kerosene instead of burning out after a while (like that do in my instance).

I personally don't need them to be more complex than that.

Maybe have two versions, one that doesn't produce fake air blocks, and one that does but uses a little more fuel to burn brighter?

Then I'd you don't want to deal with the fake air blocks you can just disable the second one.

**Comment by MineMaarten** [comment]
"one that doesn't produce fake air blocks"
By definition that means a max brightness equal of that of torches.

If you don't like the fake airblock concept (you really don't have any valid reasons to object to it, apart from problems in the _past_), simply don't use it. If you want a light source without those air blocks, use a torch. Sorry.

But like I said, thought of having an adjustable range, maybe even the torch strength. But no promises.

**Comment by Axylxys** [comment]
Out of curiosity, what changed regarding air blocks with 1.7 ? Do they all work properly, or is it just safe because most mods took care of that, and then they could still go wrong when installing some specific mod with lazy/faulty coding or something like that ?

Just trying to get an idea of this, as i remember them causing a lot of mess (from plants not growing to world corruption and chunk resets) and while i expect most mainstream mods to be well done, i'm a bit scared of playing russian roulette when testing little mods or addons from unexperienced modders that could ignore this issue and then... ouch.

While i know it's probably overreacting, as a mod user it's a bit hard to tell what's really safe. Though i'll happily use such lamps if they're safe now.

**Comment by MineMaarten** [comment]
So, in case you don't know the exact details of this 'famous' bug:

When a modder wants to check if a block at a certain location is an air block (to check if another block can be placed and such), you used to do world.getBlock(x,y,z) == Blocks.air. Blocks.air being the Vanilla air block.

Now a lot of mods have added custom air blocks, and Forge added support for them. Think about Railcraft's heat blocks (blocks that players leave behind while walking around), and all high range light emitting blocks (Thaumcraft's and Factorization's lamps). For your mod to be compatible with it you need to do world.isAirBlock(x,y,z). That checks if the block behaves like an air block rather than being equal to Vanilla's air block.

This is a change that has been put in a long time ago, and over time mods have adapted to it (including PneumaticCraft, in 1.6.4, I was just being dumb, as that Forge addition was there a long time ago even then). The adapted to it because people filed bug reports to the weird behaving mods, after which it turned out that the block they thought was air wasn't 'real' air. A lot of bugs were reported though, which is why people get all scared when seeing 'fake air blocks'.

But again, this is a long time ago. It's still possible mods do  world.getBlock(x,y,z) == Blocks.air. But the proper check is general knowledge nowadays.

And think about it: Have you had problems with Railcraft recently? Or with the high range lamps of other mods? And even if my lamps will cause weird behaviour (I doubt it), you can always just remove the lamp again, and I'll make sure to delete those fake air blocks upon lamp removal.

Also, world corruption sounds veeeeerry unlikely (and you will agree if you see the in-depth explanation I gave).

**Comment by Forecaster** [comment]
I thought that isAir was a vanilla method

And I'm wary of fake air blocks mostly since I found that even ic2 still has issues with them, even though it's supposed to be using isAir.

I guess it would be prudent to ask how far you intend to extend the radius?

The fluorescent lamps in the Floodlights mod by Keridos replace the air blocks that are directly touching the lamp with fake air blocks that emit light to extend the light radius a bit, is it something similar to that you plan on doing?

**Comment by MineMaarten** [comment]
Yes

**Comment by Axylxys** [comment]
Nice explanation, thank you !
