### ISSUE TITLE
Drone status information

### ISSUE THREAD

**Issue by Forecaster** [MineMaarten/PneumaticCraft#717]
The routine information is great for debugging programs, but not so useful to detect problems with drones or logistics setups.

I'd like there to be another field that displays the drones current status, for example if it's currently charging, or waiting for a job.

**Comment by MineMaarten** [comment]
Sounds cool. I can only think of a tag for Charging though, as a Drone never is 'waiting for a job', it will always be running a command. If it's waiting for something to to it just rushes through the program and executes only pieces that it can execute... There isn't really a 'wait'.

If I can come up with more than just 'charging' it might be interesting though..
Maybe just a tag instead that displays the name of the currently running piece? (like with the floating puzzle piece, but that one you don't see all the time as it's at the place of execution rather than the Drone's location).

**Comment by Forecaster** [comment]
I like that idea, and it could display charging there if that's what it's doing. What I'd really like though is to be able to tell if it can't execute a puzzle piece for some reason, like there is nothing to do with it, but if it's not possible it's not possible.

**Comment by MineMaarten** [comment]
THAT, I do want too ;P. I wanted that already when I implemented the 'debug' view of the floating puzzle pieces, but never implemented it fully really. This might be the time.
