### ISSUE TITLE
Crash when trying to search for item

### ISSUE THREAD

**Issue by huntert98** [MineMaarten/PneumaticCraft#776]
This happens whenever you search for an item, be it in a Pneumatic helmet or Amadron.

-- Head --
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1645)

crash report: http://pastebin.com/AV9KCRXB
if you need the whole log don't be scared to ask :)

**Comment by MineMaarten** [comment]
Hmm try going into Creative mode (not NEI) and open up the 'search' panel. I'm going to assume that crashes as well, meaning some other mod is doing it.

**Comment by huntert98** [comment]
Didn't even think about that, yes it in fact does.

When trying to open search in creative: http://pastebin.com/bpfda7mA
I didn't get much info out of that ^, hopefully you can :)

**Comment by MineMaarten** [comment]
The only info I can extract from that is that PneumaticCraft isn't the cause here, as that on its own doesn't crash creative, and neither will removing PneumaticCraft will prevent your instance from crashing in creative, I'm pretty sure.

Some mod is not behaving in creative mode, and that's the cause of the problem. Not PneumaticCraft. Sorry, you'll probably have to 'binary search' to find the offending mod.

**Comment by huntert98** [comment]
For future reference: it was Highlands-1.7.2-v-2.2.3.jar that caused it to crash.
