### ISSUE TITLE
Crash with BetterStorage Crate and Pneumatic Helmet

### ISSUE THREAD

**Issue by belathus** [MineMaarten/PneumaticCraft#809]
I got the following crash: http://pastebin.com/qbWjmMwu

It does not appear to be the same as #513.

I am running version 1.12.4, which is a month old at this point.

**Comment by copygirl** [comment]
I will just jump in here to explain what's going on:
"Tile entity inventories are server-side only, as such it doesn't make sense to check them on the client." That's what I usually tell mod developers encountering this. Does PneumaticCraft sync the inventories so the helmet can show what's inside?

Either way, crates simply throw an error whenever something accesses the IInventory stuff on the client, due to that being a mistake 99% of the time. With the way they're handled internally, the contents exposed via the IInventory aren't useful at all in this case, anyway. So my suggestion would be to either blacklist crates, or use the [ICrateStorage interface](https://github.com/copygirl/BetterStorage/blob/master/src/main/java/net/mcft/copy/betterstorage/api/crate/ICrateStorage.java).

**Comment by MineMaarten** [comment]
"Does PneumaticCraft sync the inventories so the helmet can show / check what's inside?"
Yes

I guess I'll try..catch it like I do in other parts of the helmet and add it to the blacklist dynamically when it throws exceptions.
